### PR TITLE
fixes for recent mvc.net project

### LINKED ISSUE #14: Ambiguous routing match exception
With a fresh install of Vanilla 3.3 pointing to a `netcoreapp3.1` mvc.net application (dotnet v3.1.106), I'm getting this error whenever Vanilla calls the `/jsconnect/authenticate` endpoint. Am I missing something to make it work?

```
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
Microsoft.AspNetCore.Routing.Matching.AmbiguousMatchException: The request matched multiple endpoints. Matches:

jsConnect.Controllers.JsConnectController.AuthenticateAsync (jsConnect)
jsConnect.Controllers.JsConnectController.Authenticate (jsConnect)
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.ReportAmbiguity(CandidateState[] candidateState)
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.ProcessFinalCandidates(HttpContext httpContext, CandidateState[] candidateState)
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.Select(HttpContext httpContext, CandidateState[] candidateState)
   at Microsoft.AspNetCore.Routing.Matching.DfaMatcher.MatchAsync(HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.Matching.DataSourceDependentMatcher.MatchAsync(HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

### PR DESCRIPTION
**Pull request by rudism**
Contains a couple changes that I needed to implement to get it working:
- removes `Authenticate` action since the `AuthenticateAsync` action is automatically routed to
  - closes #14 
- ignores nulls when serializing the jsonp response since it was including stuff like `message=&error=` in the payload but not the signature, resulting in an invalid signature

### CODE REVIEW

**Comment by petrsvihlik** [comment]
the changes lgtm. thanks @rudism !

File: src/jsConnect/Extensions.cs [hunk 1]
```diff
@@ -26,7 +26,11 @@ public static string ToJsonp(this object o, string callback)
 			{
 				throw new ArgumentNullException(nameof(o));
 			}
-			return $"{callback}({JsonConvert.SerializeObject(o)})";
+			var settings = new JsonSerializerSettings
+			{
+				NullValueHandling = NullValueHandling.Ignore
```
Comment (petrsvihlik) [inline src/jsConnect/Extensions.cs:31]: just one question @rudism 

I'm wondering whether it's better to have the JSON settings hardcoded here or whether to leave it up to the user as described in https://github.com/petrsvihlik/jsConnectAspNetCoreMvc#getting-started

I think your approach might be better in that you don't have to change the JSON configuration for the whole app but just for JsonP serialization here.

What are your thoughts?

Comment (petrsvihlik) [reply src/jsConnect/Extensions.cs:31]: if you agree, I'd suggest removing that part from the readme

Comment (rudism) [reply src/jsConnect/Extensions.cs:31]: @petrsvihlik The `JsonSerializerOptions` mentioned in the readme don't seem to affect the `JsonConvert` functions anyway (I had `IgnoreNullValues` set to `true` but they were still being excluded in the JsonP) so it probably makes sense to remove that anyway.

I also think localizing the settings to where it's needed is probably better, since the application may have other JSON services elsewhere that could be affected by a global configuration change.

Comment (petrsvihlik) [reply src/jsConnect/Extensions.cs:31]: ok, agreed
